### ISSUE TITLE
doesn't list all commands

### ISSUE THREAD

**Issue by teto** [Infinisil/nixbot#1]
(might be nice to support `,help` as this was both samueldr and my guess when looking for help)
I typed "," to show the help but it didn't list `,locate` as a possible command even though the command is available and works.

**Comment by infinisil** [comment]
I recently made it to not list the special commands locate, find and tell as a bad temporary fix for the command list getting too long :P. I'll have to implement some multi-stage listing.

**Comment by infinisil** [comment]
Fixed with ea2f15b889899e769f8c77955573dc2c2a582c58
