### ISSUE TITLE
Feature Request: Add `,permalink` to link to the current log of the current channel

### ISSUE THREAD

**Issue by andir** [Infinisil/nixbot#16]
Ofen I come up with some future project for myself while chatting on #nixos-chat ans other channels. I can then either copy&paste the backlog into my notes or just link to the history of the channel. I'd really like to just link to the history of the channel at the current time but I am too lazy to open up the website and figure out the right anchor. The bot could perfectly well automate this boring task for me.

Example usage:

```
andi-: ,permalink
{^_^}: andi-: Here you go https://logs.nix.samueldr.com/nixos-chat/2020-11-17#4249862;
```
The given link would then point to the line where `,permanlink` was requested in.

```
user: something important
andi-: ,permanlink -1
{^_^}: andi-: Here you go https://logs.nix.samueldr.com/nixos-chat/2020-11-17#4249861;
```
The given link would then point to the message of `user` as that was apparently important.

**Comment by infinisil** [comment]
I don't want to bother implementing the `-1` part, but just `,permalink` is now done with https://github.com/Infinisil/nixbot/commit/dbd185e6b8cc2fee2c744afaac093f8552b66953 :)
